import Head from 'next/head';
import connectDB from '../lib/mongodb';
import User from '../Models/User';

export default function Home({ users }) {
	console.log(users);
	return (
		<div>
			<Head>
				<title>Cerveceros APP</title>
				<h1>Cerveceros APP</h1>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</div>
	);
}

export async function getServerSideProps() {
	try {
		await connectDB();

		const res = await User.find({});
		const users = res.map(e => {
			const user = e.toObject();
			user._id = user._id.toString();
			return user;
		});
		return { props: { users: users } };
	} catch (error) {
		console.log(error);
	}
}
